name: Scala.js build

on:
  push:
    branches: [ scalajs ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: scalajs
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build javascript
        run: sbt fastOptJS
      - name: Checkout github pages repo
        uses: actions/checkout@v2
        with:
          repository: Ivoah/ivoah.github.io
          path: ivoah.github.io
      - name: Copy files
        run: |
          cp index.html ivoah.github.io/raytracing/
          cp *.json ivoah.github.io/raytracing/
          cp target/scala-2.13/scala-js-ray-tracer-fastopt.js ivoah.github.io/raytracing/
      - name: Commit + push
        run: |
          cd ivoah.github.io
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'Update raytracing'
          git push