name: Scala.js build

on:
  push:
    branches: [ scalajs ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - uses: actions/checkout@v2
        with:
          ref: scalajs
          path: RayTracing
      - name: Checkout github pages repo
        run: git clone --depth 1 git@github.com:Ivoah/ivoah.github.io.git
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build javascript
        working-directory: RayTracing
        run: sbt fastOptJS
      - name: Copy files
        run: |
          cp RayTracing/index.html ivoah.github.io/raytracing/
          cp RayTracing/*.json ivoah.github.io/raytracing/
          cp RayTracing/target/scala-2.13/scala-js-ray-tracer-fastopt.js ivoah.github.io/raytracing/
      - name: Commit + push
        working-directory: ivoah.github.io
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'Update raytracing'
          git push
